# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate np-survey-dev
#
name: np-survey-dev
channels:
  - conda-forge
dependencies:
  - python
  - pip
  # For analysis
  - numpy>=1.19.2
  - matplotlib>=3.3.1
  - ipython>=7.18.1
  - jupyter>=1.0.0
  # For generating site
  - sphinx>=3.2.1
  - pydata-sphinx-theme>=0.6.0
  - myst-nb>=0.10.1
  - ghp-import>=1.0.0
  - jupytext>=1.6.0
  # Install with pip
  - pip:
    - pycountry-convert>=0.7.2
